(in-package :cl-torrent)

(defun decode (sin)
  (let ((c (read-next-char sin t)))
    (decode-dispatch c sin)))

(defun decode-dispatch (c sin)
  (cond
    ((eq    c :eof)   nil)
    ((char= c #\d)    (decode-dict    c sin))
    ((char= c #\l)    (decode-list    c sin))
    ((char= c #\i)    (decode-integer c sin))
    ((digit-char-p c) (decode-string  c sin))))

(defun decode-string (c sin)
  (assert (digit-char-p c))
  (multiple-value-bind (len c)
      (slurp-decimal sin c)
    (assert (char= #\: c))
    (let* ((buf (make-array len))
           (rlen (read-sequence buf sin)))
      (assert (= rlen len))
      buf)))

(defun decode-integer (c sin)
  (assert (char= c #\i))
  (multiple-value-bind (x c)
      (slurp-decimal sin)
    (unless (char= #\e c)
      (error "Invalid integer encoding: ended with ~c" c))
    x))

(defun decode-dict (c stream)
  (assert (char= c #\d))
  (let ((h (make-hash-table)))
    h))

(defun decode-list (c sin)
  (assert (char= c #\l))
  (let ((c (read-next-char sin nil)))
    (do ((c c (read-next-char sin nil))
         (lst nil))
        ((char= c #\e) (nreverse lst))
      (setf lst
            (cons (decode-dispatch c sin) lst)))))
